use anyhow::{Context, Result};
use chrono::Local;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

use crate::utils::fs::write_file;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Checkpoint {
    pub timestamp: String,
    pub cycle: u32,
    pub current_role: String,
    pub completed_roles: Vec<String>,
    pub next_role: String,
    pub pending_tasks: Vec<String>,
    pub current_task_id: String,
    pub retry_count: u32,
}

impl Checkpoint {
    pub fn new(
        cycle: u32,
        current_role: &str,
        completed_roles: Vec<String>,
        next_role: &str,
        pending_tasks: Vec<String>,
        current_task_id: &str,
        retry_count: u32,
    ) -> Self {
        Checkpoint {
            timestamp: Local::now().format("%Y-%m-%d %H:%M:%S").to_string(),
            cycle,
            current_role: current_role.to_string(),
            completed_roles,
            next_role: next_role.to_string(),
            pending_tasks,
            current_task_id: current_task_id.to_string(),
            retry_count,
        }
    }
}

pub fn save_checkpoint(checkpoint: &Checkpoint, path: &Path) -> Result<()> {
    let reports_dir = path.join(".docs").join("reports");
    let checkpoint_path = reports_dir.join("checkpoint.md");

    let content = format!(
        r#"# Porpoise Checkpoint

<!-- This file is auto-generated by Porpoise. Do not edit manually. -->

## Metadata
- timestamp: {timestamp}
- cycle: {cycle}
- current_role: {current_role}
- next_role: {next_role}
- current_task_id: {current_task_id}
- retry_count: {retry_count}

## Completed Roles
{completed_roles}

## Pending Tasks
{pending_tasks}
"#,
        timestamp = checkpoint.timestamp,
        cycle = checkpoint.cycle,
        current_role = checkpoint.current_role,
        next_role = checkpoint.next_role,
        current_task_id = checkpoint.current_task_id,
        retry_count = checkpoint.retry_count,
        completed_roles = if checkpoint.completed_roles.is_empty() {
            "- (none)".to_string()
        } else {
            checkpoint
                .completed_roles
                .iter()
                .map(|r| format!("- {}", r))
                .collect::<Vec<_>>()
                .join("\n")
        },
        pending_tasks = if checkpoint.pending_tasks.is_empty() {
            "- (none)".to_string()
        } else {
            checkpoint
                .pending_tasks
                .iter()
                .map(|t| format!("- {}", t))
                .collect::<Vec<_>>()
                .join("\n")
        },
    );

    write_file(&checkpoint_path, &content, path)?;

    Ok(())
}

pub fn load_checkpoint(path: &Path) -> Result<Checkpoint> {
    let checkpoint_path = path.join(".docs").join("reports").join("checkpoint.md");

    let content = fs::read_to_string(&checkpoint_path)
        .with_context(|| format!("Failed to read checkpoint from {}", checkpoint_path.display()))?;

    parse_checkpoint(&content)
}

pub(crate) fn parse_checkpoint(content: &str) -> Result<Checkpoint> {
    let mut timestamp = String::new();
    let mut cycle = 1u32;
    let mut current_role = String::new();
    let mut next_role = String::new();
    let mut completed_roles: Vec<String> = Vec::new();
    let mut pending_tasks: Vec<String> = Vec::new();
    let mut current_task_id = String::new();
    let mut retry_count = 0u32;

    let mut in_completed = false;
    let mut in_pending = false;

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("## Completed Roles") {
            in_completed = true;
            in_pending = false;
            continue;
        }
        if trimmed.starts_with("## Pending Tasks") {
            in_pending = true;
            in_completed = false;
            continue;
        }
        if trimmed.starts_with("## ") {
            in_completed = false;
            in_pending = false;
        }

        if in_completed && trimmed.starts_with("- ") {
            let role = trimmed.trim_start_matches("- ").trim().to_string();
            if role != "(none)" {
                completed_roles.push(role);
            }
            continue;
        }

        if in_pending && trimmed.starts_with("- ") {
            let task = trimmed.trim_start_matches("- ").trim().to_string();
            if task != "(none)" {
                pending_tasks.push(task);
            }
            continue;
        }

        if let Some(val) = trimmed.strip_prefix("- timestamp: ") {
            timestamp = val.trim().to_string();
        } else if let Some(val) = trimmed.strip_prefix("- cycle: ") {
            cycle = val.trim().parse().unwrap_or(1);
        } else if let Some(val) = trimmed.strip_prefix("- current_role: ") {
            current_role = val.trim().to_string();
        } else if let Some(val) = trimmed.strip_prefix("- next_role: ") {
            next_role = val.trim().to_string();
        } else if let Some(val) = trimmed.strip_prefix("- current_task_id: ") {
            current_task_id = val.trim().to_string();
        } else if let Some(val) = trimmed.strip_prefix("- retry_count: ") {
            retry_count = val.trim().parse().unwrap_or(0);
        }
    }

    Ok(Checkpoint {
        timestamp,
        cycle,
        current_role,
        completed_roles,
        next_role,
        pending_tasks,
        current_task_id,
        retry_count,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_checkpoint_md() -> &'static str {
        r#"# Porpoise Checkpoint

<!-- This file is auto-generated by Porpoise. Do not edit manually. -->

## Metadata
- timestamp: 2026-04-21 10:00:00
- cycle: 3
- current_role: tester
- next_role: reviewer
- current_task_id: M1-T01
- retry_count: 2

## Completed Roles
- pm
- developer

## Pending Tasks
- (none)
"#
    }

    #[test]
    fn parse_checkpoint_normal() {
        let cp = parse_checkpoint(sample_checkpoint_md()).unwrap();
        assert_eq!(cp.cycle, 3);
        assert_eq!(cp.current_role, "tester");
        assert_eq!(cp.next_role, "reviewer");
        assert_eq!(cp.completed_roles, vec!["pm", "developer"]);
        assert!(cp.pending_tasks.is_empty());
        assert_eq!(cp.timestamp, "2026-04-21 10:00:00");
        assert_eq!(cp.current_task_id, "M1-T01");
        assert_eq!(cp.retry_count, 2);
    }

    #[test]
    fn parse_checkpoint_defaults_on_empty() {
        let cp = parse_checkpoint("# Porpoise Checkpoint\n").unwrap();
        assert_eq!(cp.cycle, 1);
        assert!(cp.current_role.is_empty());
        assert!(cp.completed_roles.is_empty());
        assert_eq!(cp.current_task_id, "");
        assert_eq!(cp.retry_count, 0);
    }

    #[test]
    fn parse_checkpoint_backward_compat_no_task_fields() {
        let old_format = "# Porpoise Checkpoint\n\n## Metadata\n- timestamp: 2026-04-21 10:00:00\n- cycle: 1\n- current_role: pm\n- next_role: developer\n\n## Completed Roles\n- (none)\n\n## Pending Tasks\n- (none)\n";
        let cp = parse_checkpoint(old_format).unwrap();
        assert_eq!(cp.cycle, 1);
        assert_eq!(cp.current_task_id, "");
        assert_eq!(cp.retry_count, 0);
    }
}
