use anyhow::{Context, Result};
use chrono::Local;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Checkpoint {
    pub timestamp: String,
    pub cycle: u32,
    pub current_role: String,
    pub completed_roles: Vec<String>,
    pub next_role: String,
    pub pending_tasks: Vec<String>,
}

impl Checkpoint {
    pub fn new(
        cycle: u32,
        current_role: &str,
        completed_roles: Vec<String>,
        next_role: &str,
        pending_tasks: Vec<String>,
    ) -> Self {
        Checkpoint {
            timestamp: Local::now().format("%Y-%m-%d %H:%M:%S").to_string(),
            cycle,
            current_role: current_role.to_string(),
            completed_roles,
            next_role: next_role.to_string(),
            pending_tasks,
        }
    }
}

pub fn save_checkpoint(checkpoint: &Checkpoint, path: &Path) -> Result<()> {
    let reports_dir = path.join(".docs").join("reports");
    fs::create_dir_all(&reports_dir)?;

    let checkpoint_path = reports_dir.join("checkpoint.md");

    let content = format!(
        r#"# Porpoise Checkpoint

<!-- This file is auto-generated by Porpoise. Do not edit manually. -->

## Metadata
- timestamp: {timestamp}
- cycle: {cycle}
- current_role: {current_role}
- next_role: {next_role}

## Completed Roles
{completed_roles}

## Pending Tasks
{pending_tasks}
"#,
        timestamp = checkpoint.timestamp,
        cycle = checkpoint.cycle,
        current_role = checkpoint.current_role,
        next_role = checkpoint.next_role,
        completed_roles = if checkpoint.completed_roles.is_empty() {
            "- (none)".to_string()
        } else {
            checkpoint
                .completed_roles
                .iter()
                .map(|r| format!("- {}", r))
                .collect::<Vec<_>>()
                .join("\n")
        },
        pending_tasks = if checkpoint.pending_tasks.is_empty() {
            "- (none)".to_string()
        } else {
            checkpoint
                .pending_tasks
                .iter()
                .map(|t| format!("- {}", t))
                .collect::<Vec<_>>()
                .join("\n")
        },
    );

    fs::write(&checkpoint_path, content)
        .with_context(|| format!("Failed to write checkpoint to {}", checkpoint_path.display()))?;

    Ok(())
}

pub fn load_checkpoint(path: &Path) -> Result<Checkpoint> {
    let checkpoint_path = path.join(".docs").join("reports").join("checkpoint.md");

    let content = fs::read_to_string(&checkpoint_path)
        .with_context(|| format!("Failed to read checkpoint from {}", checkpoint_path.display()))?;

    parse_checkpoint(&content)
}

fn parse_checkpoint(content: &str) -> Result<Checkpoint> {
    let mut timestamp = String::new();
    let mut cycle = 1u32;
    let mut current_role = String::new();
    let mut next_role = String::new();
    let mut completed_roles: Vec<String> = Vec::new();
    let mut pending_tasks: Vec<String> = Vec::new();

    let mut in_completed = false;
    let mut in_pending = false;

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("## Completed Roles") {
            in_completed = true;
            in_pending = false;
            continue;
        }
        if trimmed.starts_with("## Pending Tasks") {
            in_pending = true;
            in_completed = false;
            continue;
        }
        if trimmed.starts_with("## ") {
            in_completed = false;
            in_pending = false;
        }

        if in_completed && trimmed.starts_with("- ") {
            let role = trimmed.trim_start_matches("- ").trim().to_string();
            if role != "(none)" {
                completed_roles.push(role);
            }
            continue;
        }

        if in_pending && trimmed.starts_with("- ") {
            let task = trimmed.trim_start_matches("- ").trim().to_string();
            if task != "(none)" {
                pending_tasks.push(task);
            }
            continue;
        }

        // Parse metadata lines
        if let Some(val) = trimmed.strip_prefix("- timestamp: ") {
            timestamp = val.trim().to_string();
        } else if let Some(val) = trimmed.strip_prefix("- cycle: ") {
            cycle = val.trim().parse().unwrap_or(1);
        } else if let Some(val) = trimmed.strip_prefix("- current_role: ") {
            current_role = val.trim().to_string();
        } else if let Some(val) = trimmed.strip_prefix("- next_role: ") {
            next_role = val.trim().to_string();
        }
    }

    Ok(Checkpoint {
        timestamp,
        cycle,
        current_role,
        completed_roles,
        next_role,
        pending_tasks,
    })
}
